Metrics/AbcSize:
  Max: 18

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 110
  AllowURI: true

# TODO: Enable when rubocop#4262 is released
Style/SymbolArray:
  Enabled: false
  # MinSize: 3

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 15
