language: ruby
rvm:
  - "2.1.10"
  - "2.2.6"
  - "2.3.3"
  - "2.4.0"
before_install: gem update --system
script:
  - RUBY_ENV=travis
  - bundle exec rake test
  - bundle exec rake rubocop
# This is because coveralls doesn't yet support
# Ruby 2.4.0
# https://github.com/lemurheavy/coveralls-ruby/pull/117/files
matrix:
  allow_failures:
    - rvm: 2.4.0

